#! /bin/sh

# This script is meant to be run by TailsGreeter
# It reads /var/lib/gdm3/tails.locale for locale name
# and /var/lib/gdm3/tails.password for the password which is stored in
# the $TAILS_USER_PASSWORD variable.
# It's executed by GDM as root after user's login:
# ALWAYS: exit with 0 otherwise it'll break logon process completely.

# For whatever reason, /usr/sbin (needed by at least chpasswd and
# adduser) is not in our environment
export PATH="/usr/sbin:${PATH}"

# Import locale name
. /var/lib/gdm3/tails.locale || exit 0
if [ -z "${TAILS_LOCALE_NAME}" ] ; then
    exit 0
fi

localedef -c --quiet -f UTF-8 -i "${TAILS_LOCALE_NAME}" "${TAILS_LOCALE_NAME}".UTF-8

# Import the name of the live user
. /etc/live/config.d/username || exit 0
if [ -z "${LIVE_USERNAME}" ] ; then
    exit 0
fi

# Import password for superuser access
. /var/lib/gdm3/tails.password || exit 0

# Remove password file
rm --interactive=never -f /var/lib/gdm3/tails.password

# Check if password is actually set
if [ -z "${TAILS_USER_PASSWORD}" ] ; then
    rm -f /etc/polkit-1/localauthority.conf.d/52-tails.conf
    rm -f /etc/sudoers.d/tails.conf
    deluser "${LIVE_USERNAME}" sudo
    exit 0
fi

# Sets the password
echo "${LIVE_USERNAME}:${TAILS_USER_PASSWORD}" | chpasswd

# Makes the user sudoer and considered as admin for policykit
adduser "${LIVE_USERNAME}" sudo

# Make sudoers entry
echo "${LIVE_USERNAME} ALL=(ALL) ALL" > /etc/sudoers.d/tails.conf
chmod 0440 /etc/sudoers.d/tails.conf

# Add PolKit config
echo "[Configuration]" > /etc/polkit-1/localauthority.conf.d/52-tails.conf
echo "AdminIdentities=unix-user:${LIVE_USERNAME}" >> /etc/polkit-1/localauthority.conf.d/52-tails.conf

# Configure su-to-root to use sudo
sudo -u "${LIVE_USERNAME}" sh -c "echo 'SU_TO_ROOT_SU=sudo' >> /home/${LIVE_USERNAME}/.su-to-rootrc"

# Configure gksu to use sudo
if [ -x /usr/bin/gconftool-2 ]
then
    sudo -u "${LIVE_USERNAME}" gconftool-2 -s -t bool /apps/gksu/sudo-mode true
fi
